# Generated by Django 3.1.7 on 2021-04-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, to='ourapp.MyCourse'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ManyToManyField(blank=True, default=None, to='ourapp.MyUser'),
        ),
    ]
