# Generated by Django 3.1.7 on 2021-04-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
    ]
