# Generated by Django 3.1.7 on 2021-04-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=None)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ourapp.mycourse')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ourapp.myuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='sectionone',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Joke',
        ),
        migrations.DeleteModel(
            name='SectionOne',
        ),
    ]
