# Generated by Django 3.1.7 on 2021-04-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_auto_20210426_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('ta', 'Ta'), ('supervisor', 'Supervisor')], default=None, max_length=100),
        ),
    ]
