# Generated by Django 3.1.7 on 2021-04-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_auto_20210425_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ManyToManyField(blank=True, to='ourapp.MyCourse'),
        ),
        migrations.AlterField(
            model_name='section',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='ourapp.MyUser'),
        ),
    ]
