# Generated by Django 3.1.7 on 2021-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_auto_20210422_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=None, max_length=3),
        ),
    ]
