# Generated by Django 3.1.7 on 2021-05-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_auto_20210426_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(blank=True, default=None, to='ourapp.Skill'),
        ),
    ]
