# Generated by Django 3.1.7 on 2021-04-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_auto_20210422_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
