# Generated by Django 3.1.7 on 2021-05-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_auto_20210503_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='name',
        ),
    ]
