# Generated by Django 3.1.7 on 2021-04-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0006_auto_20210422_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='MyCourse',
        ),
    ]
