# Generated by Django 3.1.7 on 2021-04-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0007_auto_20210422_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='instructor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ourapp.myuser'),
        ),
    ]
